# Generated by Django 3.2.10 on 2022-01-28 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('mood', models.CharField(choices=[('unknown', 'Unknown'), ('happy', 'Happy'), ('anxious', 'Anxious'), ('sad', 'Sad')], default='unknown', max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
