# Generated by Django 3.2.10 on 2022-01-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellbeing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='mood',
            field=models.CharField(choices=[('tired', 'Tired'), ('bored', 'Bored'), ('stressed', 'Stressed'), ('unknown', 'Unknown'), ('happy', 'Happy'), ('anxious', 'Anxious'), ('sad', 'Sad')], default='unknown', max_length=200),
        ),
    ]
