# Generated by Django 3.2.10 on 2022-01-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellbeing', '0002_alter_mood_mood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mood',
            name='mood',
            field=models.CharField(choices=[('tired', 'Tired'), ('bored', 'Bored'), ('stressed', 'Stressed'), ('unknown', 'Unknown'), ('happy', 'Happy'), ('anxious', 'Anxious'), ('sad', 'Sad')], max_length=200),
        ),
    ]
