# Generated by Django 3.2.10 on 2022-01-31 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wellbeing', '0003_auto_20220130_1415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mood',
            options={'ordering': ['-created_on']},
        ),
    ]
